#!/usr/bin/env python3
"""
Scan all GLTF files under assets/models/ and extract bounding-box metadata.
Reads accessor min/max from all POSITION attributes across all meshes to compute
the full model extent in bind-pose (or static pose for non-skinned models).

Writes: assets/models/model_metadata.json

Stored per model:
  category       — subfolder name (Aliens, Columns, ...)
  gltf_path      — relative to assets/
  bounds_min     — [x, y, z] world-space lower corner in bind pose
  bounds_max     — [x, y, z] world-space upper corner in bind pose
  width          — x extent
  height         — y extent (vertical)
  depth          — z extent
  pivot_y_offset — -bounds_min[1], i.e. how much to raise the model so its base
                   sits at y=0 (useful for ground placement)

Usage:
    python scripts/scan_gltf_metadata.py
"""
import json
from pathlib import Path

ASSETS_DIR = Path(__file__).parent.parent / "assets"
MODELS_DIR = ASSETS_DIR / "models"
OUTPUT_PATH = MODELS_DIR / "model_metadata.json"


def extract_bounds(gltf_path):
    with open(gltf_path, encoding="utf-8") as f:
        data = json.load(f)

    accessors = data.get("accessors", [])
    meshes = data.get("meshes", [])

    # Find all POSITION accessor indices
    pos_accessor_indices = set()
    for mesh in meshes:
        for prim in mesh.get("primitives", []):
            attrs = prim.get("attributes", {})
            if "POSITION" in attrs:
                pos_accessor_indices.add(attrs["POSITION"])

    if not pos_accessor_indices:
        return None

    global_min = [float("inf")] * 3
    global_max = [float("-inf")] * 3

    for idx in pos_accessor_indices:
        if idx >= len(accessors):
            continue
        acc = accessors[idx]
        if "min" not in acc or "max" not in acc:
            continue
        mn = acc["min"]
        mx = acc["max"]
        for i in range(3):
            if mn[i] < global_min[i]:
                global_min[i] = mn[i]
            if mx[i] > global_max[i]:
                global_max[i] = mx[i]

    if global_min[0] == float("inf"):
        return None

    return global_min, global_max


def main():
    gltf_files = sorted(MODELS_DIR.rglob("*.gltf"))
    if not gltf_files:
        print("No GLTF files found.")
        return

    models = {}
    skipped = []

    for gltf_path in gltf_files:
        key = gltf_path.stem.lower()
        category = gltf_path.parent.name
        rel_path = gltf_path.relative_to(ASSETS_DIR).as_posix()

        result = extract_bounds(gltf_path)
        if result is None:
            skipped.append(key)
            continue

        mn, mx = result
        width = round(mx[0] - mn[0], 4)
        height = round(mx[1] - mn[1], 4)
        depth = round(mx[2] - mn[2], 4)

        models[key] = {
            "category": category,
            "gltf_path": rel_path,
            "bounds_min": [round(v, 4) for v in mn],
            "bounds_max": [round(v, 4) for v in mx],
            "width": width,
            "height": height,
            "depth": depth,
            "pivot_y_offset": round(-mn[1], 4),
        }

    output = {"_note": "Generated by scripts/scan_gltf_metadata.py", "models": models}
    OUTPUT_PATH.write_text(json.dumps(output, indent=2), encoding="utf-8")

    print(f"Wrote {OUTPUT_PATH.relative_to(ASSETS_DIR.parent)}")
    print(f"  {len(models)} models scanned")
    if skipped:
        print(f"  {len(skipped)} skipped (no POSITION accessor): {', '.join(skipped)}")

    # Print size summary
    widths = sorted((m["width"], k) for k, m in models.items())
    depths = sorted((m["depth"], k) for k, m in models.items())
    heights = sorted((m["height"], k) for k, m in models.items())

    print(f"\nWidth  range: {widths[0][0]:.2f} ({widths[0][1]}) .. {widths[-1][0]:.2f} ({widths[-1][1]})")
    print(f"Height range: {heights[0][0]:.2f} ({heights[0][1]}) .. {heights[-1][0]:.2f} ({heights[-1][1]})")
    print(f"Depth  range: {depths[0][0]:.2f} ({depths[0][1]}) .. {depths[-1][0]:.2f} ({depths[-1][1]})")


if __name__ == "__main__":
    main()
